feat: callback nr
defi-wonderland/aztec-private-oracle pull request #19
Opened 2023-12-05 10:18 UTC by drgorillamd

2023-12-11 17:07 UTC, 0xShaito requested changes

2023-12-11 17:07 UTC, 0xShaito commented on src/test/e2e.test.ts
> +        mockCallback.address.toBigInt(),
Can we save this array in a const?

2023-12-11 17:07 UTC, 0xShaito commented on src/test/e2e.test.ts
> +      let _ = await oracle
I don't think this has a warning if you don't save the result?

2023-12-12 18:19 UTC, 0xShaito approved these changes, later dismissed

2023-12-13 17:38 UTC, spalladino approved these changes

2023-12-13 21:31 UTC, 0xShaito approved these changes

2023-12-13 21:31 UTC, merged